---
- name: Ensure directories are created
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cache_path }}"
    - "{{ bin_dir_path }}"
  # async: 10

- name: Download binary
  include_tasks: download_binary.yml
  vars:
    repo: "{{ item }}"
  loop: "{{ repos.split(',') }}"
  # async: 10